### ISSUE TITLE
[HCA Next] Add findable-ui cookie footer banner 

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-portal#2118] opened 2023-05-12 20:36 UTC
#### Depends On
- [ ] https://github.com/DataBiosphere/findable-ui/issues/34

#### Approach
* See prod version for content:  

<img width="1641" alt="Screen Shot 2023-06-20 at 11 23 07 AM" src="https://github.com/DataBiosphere/data-portal/assets/2446424/435aa6be-3803-4bf1-9e72-ff513ad561a2">

**Comment by frano-m** [comment] 2023-12-20 06:56
Duplicate of [[Atlas Pages] Add support form and button to the home page (and all other pages)#2353](https://github.com/DataBiosphere/data-portal/issues/2353)

**Closed as completed by frano-m** 2023-12-20 06:56 UTC
