### ISSUE TITLE
HCA Metadata Schema Style and Formatting Guide has a broken link

### ISSUE THREAD

**Issue by brianraymor** [DataBiosphere/data-portal#542] opened 2019-09-24 20:56 UTC
On https://data.humancellatlas.org/metadata/design-principles/rationale#flexible

[HCA Metadata Schema Style and Formatting Guide](https://data.humancellatlas.org/metadata/design-principles/schema_style_guide) has a broken link.

**Comment by NoopDog** [comment] 2019-12-02 04:15
Closing as this is a dupe of #509.

**Closed as completed by NoopDog** 2019-12-02 04:15 UTC
